HORSE_HANDLES = [
"Ace",
"Adagio",
"Adios",
"Admiral",
"Akela",
"Alamo",
"Albert",
"Alfie",
"Allegro",
"Alto",
"Amethyst",
"Amigo",
"Amulet",
"Angel",
"Angelo",
"Apache",
"Apollo",
"Apple",
"Archie",
"Archimedes",
"Arion",
"Arizona",
"Armand",
"Arod",
"Artax",
"Ash",
"Atlanta",
"Austin",
"Badger",
"Bagel",
"Baloo",
"Bambi",
"Bandido",
"Bandit",
"Banjo",
"Barney",
"Baron",
"Barry",
"Bashful",
"Basil",
"Batman",
"Baxter",
"Bear",
"Ben",
"Bentley",
"Berlin",
"Berlioz",
"Biggles",
"Bilbo",
"Bill",
"Billy",
"Bingo",
"Biscuit",
"Blackberry",
"Blackie",
"Blake",
"Blizzard",
"Blue",
"Bluey",
"Bob",
"Bobbie",
"Bojangles",
"Bolero",
"Boris",
"Boston",
"Boxer",
"Boy",
"Bracken",
"Bramble",
"Brave",
"Braveheart",
"Bravo",
"Brego",
"Bronze",
"Brownie",
"Bruce",
"Bubble",
"Buck",
"Buddy",
"Bugsy",
"Bullet",
"Bullseye",
"Bumble",
"Bunny",
"Buster",
"Butter",
"Butterfly",
"Buttons",
"Buzz",
"Caballo",
"Cactus",
"Caesar",
"Calisson",
"Cappuccino",
"Captain",
"Caramel",
"Casino",
"Casper",
"Caviar",
"Cedar",
"Celtic",
"Champagne",
"Champion",
"Chancellor",
"Chantilly",
"Charlie",
"Charm",
"Cherokee",
"Chess",
"Chianti",
"Chico",
"Chief",
"Chips",
"Chocolate",
"Chub",
"Chucky",
"Cilantro",
"Cincinnati",
"Cinnamon",
"Classic",
"Clever",
"Cloud",
"Clover",
"Clyde",
"Cobra",
"Coco",
"Coconut",
"Colorado",
"Columbo",
"Comanche",
"Comino",
"Commodore",
"Concerto",
"Concord",
"Condor",
"Connor",
"Conquest",
"Cotton",
"Cougar",
"Courageous",
"Cowboy",
"Coyote",
"Crazy",
"Crescendo",
"Crunchie",
"Cupcake",
"Cyclone",
"Dallas",
"Dan",
"Dancer",
"Dandy",
"Dark",
"Dawson",
"Delta",
"Deputy",
"Dexter",
"Diablo",
"Diamond",
"Diego",
"Digger",
"Director",
"Disco",
"Dodger",
"Domino",
"Don Juan",
"Donald",
"Donut",
"Douglas",
"Dragon",
"Dragonfly",
"Drakkar",
"Dream",
"Dreamer",
"Drummer",
"Dubai",
"Dublin",
"Duet",
"Duke",
"Duncan",
"Dynamite",
"Eagle",
"Edgar",
"Einstein",
"Eldorado",
"Elvis",
"Emmett",
"Empire",
"Equinox",
"Eros",
"Espresso",
"Excalibur",
"Fabio",
"Faithful",
"Falcon",
"Faster",
"Feast",
"Felix",
"Finley",
"Fire",
"Firefly",
"Fizz",
"Fjord",
"Flame",
"Flamenco",
"Flash",
"Flint",
"Florence",
"Fluffy",
"Fly Away",
"Fonzie",
"Footloose",
"Forest",
"Forever",
"Fox",
"Fox Trot",
"Freddy",
"Freedom",
"French",
"Friday",
"Frodo",
"Fudge",
"Fuego",
"Gabilan",
"Galactic",
"Gambit",
"Gandalf",
"Gatsby",
"Gemini",
"General",
"Gentleman",
"George",
"Geronimo",
"Ghost",
"Ghost Rider",
"Gingerbread",
"Gino",
"Gizmo",
"Glorious",
"Golden",
"Goldeneye",
"Goldfinger",
"Goliath",
"Gouverneur",
"Graphite",
"Gray",
"Green Tea",
"Grizzly",
"Groovy",
"Gulliver",
"Hades",
"Hamilton",
"Hamlet",
"Happy",
"Harley",
"Harry",
"Harvey",
"Haughty",
"Hawk",
"Heart",
"Hector",
"Hengroen",
"Henry",
"Hercules",
"Herman",
"Hermes",
"Hero",
"Highlander",
"Horace",
"Houdini",
"Houston",
"Humphrey",
"Hunter",
"Icarus",
"Ike",
"Inca",
"Indiana",
"Indigo",
"Indy",
"Inferno",
"Irish",
"Iron",
"Izzy",
"Jack",
"Jacko",
"Jackpot",
"Jackson",
"Jason",
"Jasper",
"Jazz",
"Jazzman",
"Jedi",
"Jelly Bean",
"Jet",
"Jetset",
"Jim",
"Jimbo",
"Jiminy",
"Jimmy",
"Jingles",
"Joey",
"Joker",
"Jumper",
"Junior",
"Jupiter",
"Kelpie",
"Kid",
"King",
"Kipper",
"Kiss",
"Kiwi",
"Knight",
"Kuzco",
"Lancelot",
"Legend",
"Leo",
"Leonardo",
"Lestat",
"Level",
"Lincoln",
"Linguini",
"Lord",
"Lorenzo",
"Lottery",
"Lotus",
"Louis",
"Lucky",
"Ludwig",
"Lunatic",
"Maestro",
"Magic",
"Magic Carpet",
"Magnum",
"Majestic",
"Major",
"Malcolm",
"Malibu",
"Mambo",
"Mango",
"Marcus",
"Marley",
"Marshmallow",
"Martini",
"Marvin",
"Master",
"Matrix",
"Maverick",
"Max",
"Maximus",
"Mercury",
"Mickey",
"Midnight",
"Miles",
"Milky",
"Millennium",
"Milo",
"Milord",
"Mind",
"Minstrel",
"Miracle",
"Monday",
"Money",
"Moon",
"Morning",
"Morocco",
"Mouse",
"Mulder",
"Murphy",
"Mustang",
"Mustard",
"Mysterious",
"Napoleon",
"Nash",
"Navajo",
"Nelson",
"Nemo",
"Neon",
"Neptune",
"Nifty",
"Ninja",
"Nirvana",
"Noble",
"Notorious",
"Nougat",
"Nugget",
"Nutmeg",
"Nuts",
"Oasis",
"Ocean",
"Oliver",
"Olympic",
"Onix",
"Onyx",
"Oreo",
"Orion",
"Orlando",
"Oscar",
"Othello",
"Ozzy",
"Pablo",
"Pacific",
"Paddy",
"Paint",
"Paris",
"Partner",
"Patch",
"Patchwork",
"Patriot",
"Peanut",
"Pebbles",
"Pegasus",
"Peppercorn",
"Perfect",
"Peterpan",
"Phenomenon",
"Pheonix",
"Phoenix",
"Picasso",
"Pilgrim",
"Pilot",
"Pirate",
"Poker",
"Polar",
"Poleaxe",
"Pongo",
"Pony Express",
"Port",
"Powder",
"Pride",
"Prince",
"Prize",
"Pumpkin",
"Punch",
"Punk",
"Puzzle",
"Quantum",
"Quest",
"Quick",
"Quicky",
"Racer",
"Rain",
"Rainbow",
"Raindrop",
"Rambo",
"Rapid",
"Ratatouille",
"Red",
"Red",
"Reflection",
"Rembrandt",
"Resplendent",
"Rhubarb",
"Rico",
"Ring",
"Rio",
"Rocco",
"Rock",
"Rocket",
"Rocky",
"Rodeo",
"Roger",
"Romeo",
"Royal",
"Rudolph",
"Rufus",
"Rusty",
"Santiago",
"Saturn",
"Scooby",
"Seamus",
"Secret",
"Selection",
"Sesamo",
"Seth",
"Shadow",
"Shorty",
"Sidney",
"Silence",
"Silver",
"Simba",
"Sky",
"Smokey",
"Snoopy",
"Snow",
"Snowball",
"Snowy",
"Socks",
"Sonic",
"Sonny",
"Sorcerer",
"Spain",
"Special",
"Speedy",
"Spice",
"Spider",
"Spirit",
"Splash",
"Spooky",
"Stanley",
"Star",
"Storm",
"Stormy",
"Story",
"Sudoku",
"Sueno",
"Sugar",
"Sultan",
"Sunlight",
"Sunny",
"Sunrise",
"Sunset",
"Survivor",
"Sweet",
"Sweety",
"Tabasco",
"Tahiti",
"Tango",
"Tank",
"Tap Dance",
"Tarot",
"Tarzan",
"Tattoo",
"Taxi",
"Taz",
"Teddy",
"Teddy Bear",
"Tempo",
"Tennessee",
"Texas",
"Thor",
"Thunder",
"Thunderstorm",
"Tiger",
"Tigger",
"Toby",
"Toffee",
"Tonto",
"Top Hat",
"Topaz",
"Tornado",
"Toronto",
"Travel",
"Traveler",
"Treacle",
"Treasure",
"Tristan",
"Triton",
"Truffles",
"Tucker",
"Twain",
"Twist",
"Tyson",
"Tzar",
"Uno",
"Vegas",
"Victorious",
"Viking",
"Vito",
"Volcanic",
"Volcano",
"Warrior",
"Watson",
"Welcome",
"Western",
"Whiskey",
"Whisper",
"White",
"Whitewater",
"Wild",
"Wildfire",
"Willow",
"Willy",
"Wind Song",
"Windsor",
"Winston",
"Wizard",
"Wolf",
"Wombat",
"Wonder",
"Woodstock",
"Woody",
"Working",
"Xanadu",
"Xanthos",
"Yankee",
"Yellow",
"Ying Yang",
"Yoda",
"Yohi",
"Yosemite",
"Yoshi",
"Young",
"Zanzibar",
"Zed",
"Zen",
"Zephyr",
"Ziggy",
"Zip",
"Zorro",
]

COUNTRY_POPULATION = [
 {
   "country": "Afghanistan",
   "iso3166": 4,
   "population": 171200,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Albania",
   "iso3166": 8,
   "population": 31729,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Antarctica",
   "iso3166": 10,
   "population": 31729,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Algeria",
   "iso3166": 12,
   "population": 44991,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "American Samoa",
   "iso3166": 16,
   "population": 44991,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Andorra",
   "iso3166": 20,
   "population": 44991,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Angola",
   "iso3166": 24,
   "population": 1013,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Antigua and Barbuda",
   "iso3166": 28,
   "population": 493,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Azerbaijan",
   "iso3166": 31,
   "population": 71606,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Argentina",
   "iso3166": 32,
   "population": 2447582,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Australia",
   "iso3166": 36,
   "population": 268739,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Austria",
   "iso3166": 40,
   "population": 93225,
   "pct_registered": 0.8,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Bahamas",
   "iso3166": 44,
   "population": 0,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Bahrain",
   "iso3166": 48,
   "population": 0,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Bangladesh",
   "iso3166": 50,
   "population": 0,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Armenia",
   "iso3166": 51,
   "population": 11402,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Barbados",
   "iso3166": 52,
   "population": 1259,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Belgium",
   "iso3166": 56,
   "population": 35079,
   "pct_registered": 0.8,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Bermuda",
   "iso3166": 60,
   "population": 1012,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Bhutan",
   "iso3166": 64,
   "population": 13914,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Bolivia",
   "iso3166": 68,
   "population": 499403,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Bosnia and Herzegovina",
   "iso3166": 70,
   "population": 16288,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Botswana",
   "iso3166": 72,
   "population": 34737,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Bouvet Island",
   "iso3166": 74,
   "population": 34737,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Brazil",
   "iso3166": 76,
   "population": 5577539,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Belize",
   "iso3166": 84,
   "population": 5919,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "British Indian Ocean Territory",
   "iso3166": 86,
   "population": 100,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Solomon Islands",
   "iso3166": 90,
   "population": 152,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Virgin Islands (British)",
   "iso3166": 92,
   "population": 152,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Brunei Darussalam",
   "iso3166": 96,
   "population": 152,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Bulgaria",
   "iso3166": 100,
   "population": 53614,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Myanmar",
   "iso3166": 104,
   "population": 102973,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Burundi",
   "iso3166": 108,
   "population": 102973,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Belarus",
   "iso3166": 112,
   "population": 55800,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Cambodia",
   "iso3166": 116,
   "population": 30025,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Cameroon",
   "iso3166": 120,
   "population": 18007,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Canada",
   "iso3166": 124,
   "population": 398802,
   "pct_registered": 0.8,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 319041
 },
 {
   "country": "Cabo Verde",
   "iso3166": 132,
   "population": 559,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Cayman Islands",
   "iso3166": 136,
   "population": 559,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Central African Republic",
   "iso3166": 140,
   "population": 559,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Sri Lanka",
   "iso3166": 144,
   "population": 1379,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Chad",
   "iso3166": 148,
   "population": 437566,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Chile",
   "iso3166": 152,
   "population": 245507,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "China",
   "iso3166": 156,
   "population": 5910792,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Taiwan Province of China",
   "iso3166": 158,
   "population": 5910792,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Christmas Island",
   "iso3166": 162,
   "population": 5910792,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Cocos (Keeling) Islands",
   "iso3166": 166,
   "population": 5910792,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Colombia",
   "iso3166": 170,
   "population": 763505,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Comoros",
   "iso3166": 174,
   "population": 763505,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Mayotte",
   "iso3166": 175,
   "population": 763505,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Congo",
   "iso3166": 178,
   "population": 78,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Congo (Democratic Republic of the)",
   "iso3166": 180,
   "population": 78,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Cook Islands",
   "iso3166": 184,
   "population": 303,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Costa Rica",
   "iso3166": 188,
   "population": 127793,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Croatia",
   "iso3166": 191,
   "population": 22775,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Cuba",
   "iso3166": 192,
   "population": 860800,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Cyprus",
   "iso3166": 196,
   "population": 660,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Czechia",
   "iso3166": 203,
   "population": 0,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Benin",
   "iso3166": 204,
   "population": 1019,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Denmark",
   "iso3166": 208,
   "population": 51282,
   "pct_registered": 0.8,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Dominica",
   "iso3166": 212,
   "population": 51282,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Dominican Republic",
   "iso3166": 214,
   "population": 358766,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Ecuador",
   "iso3166": 218,
   "population": 219134,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "El Salvador",
   "iso3166": 222,
   "population": 97753,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Equatorial Guinea",
   "iso3166": 226,
   "population": 97753,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Ethiopia",
   "iso3166": 231,
   "population": 2158176,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Eritrea",
   "iso3166": 232,
   "population": 2158176,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Estonia",
   "iso3166": 233,
   "population": 6314,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Faroe Islands",
   "iso3166": 234,
   "population": 6314,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Falkland Islands (Malvinas)",
   "iso3166": 238,
   "population": 1157,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "South Georgia and the South Sandwich Islands",
   "iso3166": 239,
   "population": 1157,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Fiji",
   "iso3166": 242,
   "population": 47159,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Finland",
   "iso3166": 246,
   "population": 74200,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Aland Islands",
   "iso3166": 248,
   "population": 74200,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "France",
   "iso3166": 250,
   "population": 379554,
   "pct_registered": 0.8,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 303643
 },
 {
   "country": "French Guiana",
   "iso3166": 254,
   "population": 950,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "French Polynesia",
   "iso3166": 258,
   "population": 2200,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "French Southern Territories",
   "iso3166": 260,
   "population": 2200,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Djibouti",
   "iso3166": 262,
   "population": 2200,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Gabon",
   "iso3166": 266,
   "population": 2200,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Georgia",
   "iso3166": 268,
   "population": 40032,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Gambia",
   "iso3166": 270,
   "population": 8837,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Palestine State of",
   "iso3166": 275,
   "population": 8837,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Germany",
   "iso3166": 276,
   "population": 441954,
   "pct_registered": 0.8,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 353563
 },
 {
   "country": "Ghana",
   "iso3166": 288,
   "population": 2932,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Gibraltar",
   "iso3166": 292,
   "population": 2932,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Kiribati",
   "iso3166": 296,
   "population": 2932,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Greece",
   "iso3166": 300,
   "population": 27344,
   "pct_registered": 0.8,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 21875
 },
 {
   "country": "Greenland",
   "iso3166": 304,
   "population": 152,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Grenada",
   "iso3166": 308,
   "population": 30,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Guadeloupe",
   "iso3166": 312,
   "population": 53,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Guam",
   "iso3166": 316,
   "population": 54,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Guatemala",
   "iso3166": 320,
   "population": 131583,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Guinea",
   "iso3166": 324,
   "population": 3531,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Guyana",
   "iso3166": 328,
   "population": 2412,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Haiti",
   "iso3166": 332,
   "population": 503739,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Heard Island and McDonald Islands",
   "iso3166": 334,
   "population": 503739,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Holy See",
   "iso3166": 336,
   "population": 503739,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Honduras",
   "iso3166": 340,
   "population": 181280,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Hong Kong",
   "iso3166": 344,
   "population": 181280,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Hungary",
   "iso3166": 348,
   "population": 60000,
   "pct_registered": 0.8,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Iceland",
   "iso3166": 352,
   "population": 72000,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "India",
   "iso3166": 356,
   "population": 623325,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Indonesia",
   "iso3166": 360,
   "population": 437570,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Iran (Islamic Republic of)",
   "iso3166": 364,
   "population": 131405,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Iraq",
   "iso3166": 368,
   "population": 49885,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Ireland",
   "iso3166": 372,
   "population": 92200,
   "pct_registered": 0.8,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 73760
 },
 {
   "country": "Israel",
   "iso3166": 376,
   "population": 4000,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Italy",
   "iso3166": 380,
   "population": 388324,
   "pct_registered": 0.8,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Côte d'Ivoire",
   "iso3166": 384,
   "population": 388324,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Jamaica",
   "iso3166": 388,
   "population": 4009,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Japan",
   "iso3166": 392,
   "population": 14959,
   "pct_registered": 0.8,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Kazakhstan",
   "iso3166": 398,
   "population": 2070273,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Jordan",
   "iso3166": 400,
   "population": 2249,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Kenya",
   "iso3166": 404,
   "population": 2088,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Korea (Democratic People's Republic of)",
   "iso3166": 408,
   "population": 2088,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Korea (Republic of)",
   "iso3166": 410,
   "population": 2088,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Kuwait",
   "iso3166": 414,
   "population": 1213,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Kyrgyzstan",
   "iso3166": 417,
   "population": 467249,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Lao People's Democratic Republic",
   "iso3166": 418,
   "population": 21328,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Lebanon",
   "iso3166": 422,
   "population": 3229,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Lesotho",
   "iso3166": 426,
   "population": 51898,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Latvia",
   "iso3166": 428,
   "population": 9300,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Liberia",
   "iso3166": 430,
   "population": 9300,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Libya",
   "iso3166": 434,
   "population": 45520,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Liechtenstein",
   "iso3166": 438,
   "population": 266,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Lithuania",
   "iso3166": 440,
   "population": 17321,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Luxembourg",
   "iso3166": 442,
   "population": 4535,
   "pct_registered": 0.8,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Macao",
   "iso3166": 446,
   "population": 4535,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Madagascar",
   "iso3166": 450,
   "population": 498,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Malawi",
   "iso3166": 454,
   "population": 49,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Malaysia",
   "iso3166": 458,
   "population": 3673,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Maldives",
   "iso3166": 462,
   "population": 3673,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Mali",
   "iso3166": 466,
   "population": 549316,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Malta",
   "iso3166": 470,
   "population": 1070,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 10
 },
 {
   "country": "Martinique",
   "iso3166": 474,
   "population": 1100,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Mauritania",
   "iso3166": 478,
   "population": 67020,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Mauritius",
   "iso3166": 480,
   "population": 150,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Mexico",
   "iso3166": 484,
   "population": 6378267,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 63782
 },
 {
   "country": "Monaco",
   "iso3166": 492,
   "population": 6378267,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Mongolia",
   "iso3166": 496,
   "population": 3635489,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Moldova (Republic of)",
   "iso3166": 498,
   "population": 3635489,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Montenegro",
   "iso3166": 499,
   "population": 4422,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Montserrat",
   "iso3166": 500,
   "population": 4422,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Morocco",
   "iso3166": 504,
   "population": 180000,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Mozambique",
   "iso3166": 508,
   "population": 180000,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Oman",
   "iso3166": 512,
   "population": 180000,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Namibia",
   "iso3166": 516,
   "population": 45533,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Nauru",
   "iso3166": 520,
   "population": 45533,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Nepal",
   "iso3166": 524,
   "population": 45533,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Netherlands",
   "iso3166": 528,
   "population": 139804,
   "pct_registered": 0.8,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Curaçao",
   "iso3166": 531,
   "population": 139804,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Aruba",
   "iso3166": 533,
   "population": 0,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Sint Maarten (Dutch part)",
   "iso3166": 534,
   "population": 0,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Bonaire Sint Eustatius and Saba",
   "iso3166": 535,
   "population": 0,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "New Caledonia",
   "iso3166": 540,
   "population": 11250,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Vanuatu",
   "iso3166": 548,
   "population": 7169,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "New Zealand",
   "iso3166": 554,
   "population": 48801,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Nicaragua",
   "iso3166": 558,
   "population": 268358,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Niger",
   "iso3166": 562,
   "population": 248200,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Nigeria",
   "iso3166": 566,
   "population": 102356,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Niue",
   "iso3166": 570,
   "population": 102356,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Norfolk Island",
   "iso3166": 574,
   "population": 102356,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Norway",
   "iso3166": 578,
   "population": 34958,
   "pct_registered": 0.8,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Northern Mariana Islands",
   "iso3166": 580,
   "population": 34958,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "United States Minor Outlying Islands",
   "iso3166": 581,
   "population": 34958,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Micronesia (Federated States of)",
   "iso3166": 583,
   "population": 34958,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Marshall Islands",
   "iso3166": 584,
   "population": 34958,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Palau",
   "iso3166": 585,
   "population": 34958,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Pakistan",
   "iso3166": 586,
   "population": 364870,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Panama",
   "iso3166": 591,
   "population": 106687,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 1066
 },
 {
   "country": "Papua New Guinea",
   "iso3166": 598,
   "population": 2048,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Paraguay",
   "iso3166": 600,
   "population": 275371,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Peru",
   "iso3166": 604,
   "population": 749032,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Philippines",
   "iso3166": 608,
   "population": 246271,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Pitcairn",
   "iso3166": 612,
   "population": 246271,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Poland",
   "iso3166": 616,
   "population": 188528,
   "pct_registered": 0.8,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Portugal",
   "iso3166": 620,
   "population": 37000,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Guinea-Bissau",
   "iso3166": 624,
   "population": 2426,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Timor-Leste",
   "iso3166": 626,
   "population": 52143,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Puerto Rico",
   "iso3166": 630,
   "population": 5848,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Qatar",
   "iso3166": 634,
   "population": 39429,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Réunion",
   "iso3166": 638,
   "population": 382,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Romania",
   "iso3166": 642,
   "population": 503466,
   "pct_registered": 0.8,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Russian Federation",
   "iso3166": 643,
   "population": 1374210,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Rwanda",
   "iso3166": 646,
   "population": 1374210,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Saint Barthelemy",
   "iso3166": 652,
   "population": 1374210,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Saint Helena and Ascension and Tristan da Cunha",
   "iso3166": 654,
   "population": 0,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Saint Kitts and Nevis",
   "iso3166": 659,
   "population": 0,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Anguilla",
   "iso3166": 660,
   "population": 0,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Saint Lucia",
   "iso3166": 662,
   "population": 1116,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Saint Martin (French part)",
   "iso3166": 663,
   "population": 1116,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Saint Pierre and Miquelon",
   "iso3166": 666,
   "population": 0,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Saint Vincent and the Grenadines",
   "iso3166": 670,
   "population": 0,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "San Marino",
   "iso3166": 674,
   "population": 0,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Sao Tome and Principe",
   "iso3166": 678,
   "population": 296,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Saudi Arabia",
   "iso3166": 682,
   "population": 33731,
   "pct_registered": 0.8,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Senegal",
   "iso3166": 686,
   "population": 549880,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Serbia",
   "iso3166": 688,
   "population": 15337,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Seychelles",
   "iso3166": 690,
   "population": 15337,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Sierra Leone",
   "iso3166": 694,
   "population": 436036,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Singapore",
   "iso3166": 702,
   "population": 436036,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Slovakia",
   "iso3166": 703,
   "population": 6866,
   "pct_registered": 0.8,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Viet Nam",
   "iso3166": 704,
   "population": 54117,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Slovenia",
   "iso3166": 705,
   "population": 22954,
   "pct_registered": 0.8,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Somalia",
   "iso3166": 706,
   "population": 889,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "South Africa",
   "iso3166": 710,
   "population": 320787,
   "pct_registered": 0.8,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Zimbabwe",
   "iso3166": 716,
   "population": 28219,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 282
 },
 {
   "country": "Spain",
   "iso3166": 724,
   "population": 293449,
   "pct_registered": 0.8,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "South Sudan",
   "iso3166": 728,
   "population": 0,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Sudan",
   "iso3166": 729,
   "population": 790086,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Western Sahara",
   "iso3166": 732,
   "population": 790086,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Suriname",
   "iso3166": 740,
   "population": 279,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Svalbard and Jan Mayen",
   "iso3166": 744,
   "population": 279,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Swaziland",
   "iso3166": 748,
   "population": 1673,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Sweden",
   "iso3166": 752,
   "population": 101247,
   "pct_registered": 0.9,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Switzerland",
   "iso3166": 756,
   "population": 55662,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Syrian Arab Republic",
   "iso3166": 760,
   "population": 13692,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Tajikistan",
   "iso3166": 762,
   "population": 78765,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Thailand",
   "iso3166": 764,
   "population": 19263,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Togo",
   "iso3166": 768,
   "population": 1814,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Tokelau",
   "iso3166": 772,
   "population": 1814,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Tonga",
   "iso3166": 776,
   "population": 11874,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Trinidad and Tobago",
   "iso3166": 780,
   "population": 1435,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "United Arab Emirates",
   "iso3166": 784,
   "population": 417898,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Tunisia",
   "iso3166": 788,
   "population": 57281,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Turkey",
   "iso3166": 792,
   "population": 122704,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Turkmenistan",
   "iso3166": 795,
   "population": 25975,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Turks and Caicos Islands",
   "iso3166": 796,
   "population": 25975,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Tuvalu",
   "iso3166": 798,
   "population": 25975,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Uganda",
   "iso3166": 800,
   "population": 25975,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Ukraine",
   "iso3166": 804,
   "population": 305800,
   "pct_registered": 0.8,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Macedonia (the former Yugoslav Republic of)",
   "iso3166": 807,
   "population": 305800,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Egypt",
   "iso3166": 818,
   "population": 75663,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "UK",
   "iso3166": 826,
   "population": 75663,
   "pct_registered": 0.8,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 60530
 },
 {
   "country": "Guernsey",
   "iso3166": 831,
   "population": 75663,
   "pct_registered": 0.8,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Jersey",
   "iso3166": 832,
   "population": 75663,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Isle of Man",
   "iso3166": 833,
   "population": 75663,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Tanzania, United Republic of",
   "iso3166": 834,
   "population": 75663,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "USA",
   "iso3166": 840,
   "population": 10525766,
   "pct_registered": 0.8,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 8420612
 },
 {
   "country": "Virgin Islands (U.S.)",
   "iso3166": 850,
   "population": 10525766,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Burkina Faso",
   "iso3166": 854,
   "population": 41053,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Uruguay",
   "iso3166": 858,
   "population": 415000,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Uzbekistan",
   "iso3166": 860,
   "population": 216900,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Venezuela (Bolivarian Republic of)",
   "iso3166": 862,
   "population": 527031,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Wallis and Futuna",
   "iso3166": 876,
   "population": 175,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Samoa",
   "iso3166": 882,
   "population": 1927,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Yemen",
   "iso3166": 887,
   "population": 1961,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 },
 {
   "country": "Zambia",
   "iso3166": 894,
   "population": 1961,
   "pct_registered": 0.01,
   "confidence in pct_reg": 0,
   "source of pct_reg": "Guess",
   "pick": 0
 }
]

PIOS = [
 {
   "name": "French Horse - Non-TB",
   "full_org_id": "250001",
   "country": 250,
   "org_id": "001",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "AHA : code for Arabs born in Panama only",
   "full_org_id": "591001",
   "country": 591,
   "org_id": "001",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "American Bucksin Registry association",
   "full_org_id": "840001",
   "country": 840,
   "org_id": "001",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "AHSB : code for Arabs born in Greece only",
   "full_org_id": "300002",
   "country": 300,
   "org_id": "002",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "AHSB : code for Arabs born in Malta only",
   "full_org_id": "470002",
   "country": 470,
   "org_id": "002",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "AWR : for Mexican AWR only",
   "full_org_id": "484002",
   "country": 484,
   "org_id": "002",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Anglo European Studbook",
   "full_org_id": "826002",
   "country": 826,
   "org_id": "002",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "American Hackney Horse Society",
   "full_org_id": "840002",
   "country": 840,
   "org_id": "002",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Irish Piebald and Skewbald Association",
   "full_org_id": "372003",
   "country": 372,
   "org_id": "003",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "KWPN - NA : code for horses born in Mexico",
   "full_org_id": "484003",
   "country": 484,
   "org_id": "003",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "British Association for the Purebred Spanish Horse",
   "full_org_id": "826003",
   "country": 826,
   "org_id": "003",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "American Holsteiner Horse Association Inc",
   "full_org_id": "840003",
   "country": 840,
   "org_id": "003",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "The Connemara Pony Breeders Society",
   "full_org_id": "372004",
   "country": 372,
   "org_id": "004",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "AHA : code for Arabs born in Mexico only",
   "full_org_id": "484004",
   "country": 484,
   "org_id": "004",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "American Miniature Horse Association",
   "full_org_id": "840004",
   "country": 840,
   "org_id": "004",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "AHHA : Code for holsteiner horses born in Mexico only",
   "full_org_id": "484005",
   "country": 484,
   "org_id": "005",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "British Appaloosa Society",
   "full_org_id": "826005",
   "country": 826,
   "org_id": "005",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "American paint Horse Association",
   "full_org_id": "840005",
   "country": 840,
   "org_id": "005",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "AWR : for canadian AWR only",
   "full_org_id": "124006",
   "country": 124,
   "org_id": "006",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Irish Cob Society",
   "full_org_id": "372006",
   "country": 372,
   "org_id": "006",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "British Hanoverian Horse Society",
   "full_org_id": "826006",
   "country": 826,
   "org_id": "006",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "American Quarter Horse Association",
   "full_org_id": "840006",
   "country": 840,
   "org_id": "006",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "KWPN - NA : code for horses born in Canada",
   "full_org_id": "124007",
   "country": 124,
   "org_id": "007",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Code for Irish Standard and Trotting Horses only",
   "full_org_id": "372007",
   "country": 372,
   "org_id": "007",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "American Trakehner Association, Inc",
   "full_org_id": "840007",
   "country": 840,
   "org_id": "007",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "AHSB : code for Arabs born in Ireland only",
   "full_org_id": "372008",
   "country": 372,
   "org_id": "008",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "British miniature Horse Society",
   "full_org_id": "826008",
   "country": 826,
   "org_id": "008",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "American Warmblood Registry",
   "full_org_id": "840008",
   "country": 840,
   "org_id": "008",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Irish Pony Society",
   "full_org_id": "372009",
   "country": 372,
   "org_id": "009",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "British Morgan Horse Society",
   "full_org_id": "826009",
   "country": 826,
   "org_id": "009",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "American Warmblood Society",
   "full_org_id": "840009",
   "country": 840,
   "org_id": "009",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Irish Warmblood Stud Book Ltd",
   "full_org_id": "372010",
   "country": 372,
   "org_id": "010",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "British Palomino Horse Society",
   "full_org_id": "826010",
   "country": 826,
   "org_id": "010",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "American White/american Creme Horse registry",
   "full_org_id": "840010",
   "country": 840,
   "org_id": "010",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "British Percheron horse Society",
   "full_org_id": "826011",
   "country": 826,
   "org_id": "011",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Appaloosa Horse Club",
   "full_org_id": "840011",
   "country": 840,
   "org_id": "011",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Irish Appaloosa Association",
   "full_org_id": "372012",
   "country": 372,
   "org_id": "012",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "American Quarter Horse Association UK",
   "full_org_id": "826012",
   "country": 826,
   "org_id": "012",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Arabian Horse Association",
   "full_org_id": "840012",
   "country": 840,
   "org_id": "012",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "British Skewbald & Piebald Association",
   "full_org_id": "826013",
   "country": 826,
   "org_id": "013",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "International Bucksin Horse Association INC",
   "full_org_id": "840014",
   "country": 840,
   "org_id": "014",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "British Spotted Pony Society",
   "full_org_id": "826015",
   "country": 826,
   "org_id": "015",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Warmblood Breeders Studbook- UK",
   "full_org_id": "826016",
   "country": 826,
   "org_id": "016",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Oldenburg Horse Breeders Society",
   "full_org_id": "840016",
   "country": 840,
   "org_id": "016",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Caspian Horse Society",
   "full_org_id": "826017",
   "country": 826,
   "org_id": "017",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Oldenburg Registry North America",
   "full_org_id": "840017",
   "country": 840,
   "org_id": "017",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Cleveland Bay Horse Society",
   "full_org_id": "826018",
   "country": 826,
   "org_id": "018",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Palomino Horse Breeders of America, INC",
   "full_org_id": "840018",
   "country": 840,
   "org_id": "018",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Peruvian Paso Horse Registry of North America",
   "full_org_id": "840019",
   "country": 840,
   "org_id": "019",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Dales Pony Society",
   "full_org_id": "826020",
   "country": 826,
   "org_id": "020",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Pinto Horse Association of America, INC",
   "full_org_id": "840020",
   "country": 840,
   "org_id": "020",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Dartmoor Pony Society",
   "full_org_id": "826021",
   "country": 826,
   "org_id": "021",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Pony of the Americas Club, INC",
   "full_org_id": "840021",
   "country": 840,
   "org_id": "021",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Donkey Breed Society",
   "full_org_id": "826022",
   "country": 826,
   "org_id": "022",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Swedish Warmblod Association of North America",
   "full_org_id": "840022",
   "country": 840,
   "org_id": "022",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "English Connemara Pony Society",
   "full_org_id": "826023",
   "country": 826,
   "org_id": "023",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "The american Hanoverian Society",
   "full_org_id": "840023",
   "country": 840,
   "org_id": "023",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Eriskay Pony Society",
   "full_org_id": "826024",
   "country": 826,
   "org_id": "024",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "The american Morgan Horse Association",
   "full_org_id": "840024",
   "country": 840,
   "org_id": "024",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Oldenburg Registry N.A. : Code for horses born in Canada only",
   "full_org_id": "124025",
   "country": 124,
   "org_id": "025",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Exmoor Pony Society",
   "full_org_id": "826025",
   "country": 826,
   "org_id": "025",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "KWPN - NA : code for horses born in USA",
   "full_org_id": "840025",
   "country": 840,
   "org_id": "025",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "KWPN - NA : code for horses born in USA",
   "full_org_id": "840025",
   "country": 840,
   "org_id": "025",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "ISR Pony : Code for Ponies born in Canada only",
   "full_org_id": "124026",
   "country": 124,
   "org_id": "026",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Spotted Pony Breed Society (Great Britain)",
   "full_org_id": "826026",
   "country": 826,
   "org_id": "026",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "PAHR : code the Arabs born in USA only",
   "full_org_id": "840026",
   "country": 840,
   "org_id": "026",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Fell Pony Society",
   "full_org_id": "826027",
   "country": 826,
   "org_id": "027",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "The United States Trotting Association",
   "full_org_id": "840027",
   "country": 840,
   "org_id": "027",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "PAHR : code for Arabs born in Canada only",
   "full_org_id": "124028",
   "country": 124,
   "org_id": "028",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Fjord Horse National Stud Book Association of Great Britain",
   "full_org_id": "826028",
   "country": 826,
   "org_id": "028",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Welsh Pony and Cob Society of America",
   "full_org_id": "840028",
   "country": 840,
   "org_id": "028",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Welsh Pony and Cob Society of America",
   "full_org_id": "840028",
   "country": 840,
   "org_id": "028",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Welsh Pony and Cob Society of America",
   "full_org_id": "840028",
   "country": 840,
   "org_id": "028",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Welsh Pony and Cob Society of America",
   "full_org_id": "840028",
   "country": 840,
   "org_id": "028",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "AHHA : Code for holsteiner horses born in Canada only",
   "full_org_id": "124029",
   "country": 124,
   "org_id": "029",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "FHSGI - English Friesan horses only",
   "full_org_id": "826029",
   "country": 826,
   "org_id": "029",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Norwegian Fjord Horse Registry",
   "full_org_id": "840029",
   "country": 840,
   "org_id": "029",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "AHS : Code for Hanoverian horse born in canada only",
   "full_org_id": "124030",
   "country": 124,
   "org_id": "030",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Hackney Horse Society",
   "full_org_id": "826030",
   "country": 826,
   "org_id": "030",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "North American Shagya Society",
   "full_org_id": "840030",
   "country": 840,
   "org_id": "030",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Highland Pony Society",
   "full_org_id": "826031",
   "country": 826,
   "org_id": "031",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "International Sport Horse Registry",
   "full_org_id": "840031",
   "country": 840,
   "org_id": "031",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Icelandic Horse Society",
   "full_org_id": "826032",
   "country": 826,
   "org_id": "032",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Lipizzan Association of America",
   "full_org_id": "840032",
   "country": 840,
   "org_id": "032",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "International miniature Pony",
   "full_org_id": "826033",
   "country": 826,
   "org_id": "033",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Irish Draught Horse Society of North America",
   "full_org_id": "840033",
   "country": 840,
   "org_id": "033",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Irish Draught Horse Society",
   "full_org_id": "826034",
   "country": 826,
   "org_id": "034",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Lipizzaner national stud book association of Great Britain",
   "full_org_id": "826035",
   "country": 826,
   "org_id": "035",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "International Curly Horse Organization",
   "full_org_id": "840035",
   "country": 840,
   "org_id": "035",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Nokota Horse Conservancy",
   "full_org_id": "840036",
   "country": 840,
   "org_id": "036",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "National Pony Society",
   "full_org_id": "826037",
   "country": 826,
   "org_id": "037",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Friesian Horse Society Inc",
   "full_org_id": "840037",
   "country": 840,
   "org_id": "037",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "New Forest Pony Breeding & Cattle Society",
   "full_org_id": "826038",
   "country": 826,
   "org_id": "038",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Continental Stud Book",
   "full_org_id": "840038",
   "country": 840,
   "org_id": "038",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Shetland Pony Stud-book Society",
   "full_org_id": "826039",
   "country": 826,
   "org_id": "039",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Friesian Sporthorse Association",
   "full_org_id": "840039",
   "country": 840,
   "org_id": "039",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Shire Horse Society",
   "full_org_id": "826040",
   "country": 826,
   "org_id": "040",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Sport Horse Breeding of Great Britain",
   "full_org_id": "826041",
   "country": 826,
   "org_id": "041",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "American Heritage Horse Association",
   "full_org_id": "840041",
   "country": 840,
   "org_id": "041",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Spotted Horse and Pony Register",
   "full_org_id": "826042",
   "country": 826,
   "org_id": "042",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Spanish Mustang Registry, Inc.",
   "full_org_id": "840042",
   "country": 840,
   "org_id": "042",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Suffolk Horse Society",
   "full_org_id": "826043",
   "country": 826,
   "org_id": "043",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "California Vaquero Horse Association",
   "full_org_id": "840043",
   "country": 840,
   "org_id": "043",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Arab Horse Society",
   "full_org_id": "826044",
   "country": 826,
   "org_id": "044",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "United States Icelandic Horse Congress",
   "full_org_id": "840044",
   "country": 840,
   "org_id": "044",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Trakehner Breeders Fraternity",
   "full_org_id": "826045",
   "country": 826,
   "org_id": "045",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Horse of the Americas Registry",
   "full_org_id": "840045",
   "country": 840,
   "org_id": "045",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Horse of the Americas Registry",
   "full_org_id": "840045",
   "country": 840,
   "org_id": "045",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Welsh Pony & Cob Society",
   "full_org_id": "826046",
   "country": 826,
   "org_id": "046",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "The Akhal-Teke Horse Registry",
   "full_org_id": "840046",
   "country": 840,
   "org_id": "046",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "The Scottish Sport Horse",
   "full_org_id": "826047",
   "country": 826,
   "org_id": "047",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Weatherbys - Code for non-TB horses born in Great Britain only",
   "full_org_id": "826048",
   "country": 826,
   "org_id": "048",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "British Driving Society",
   "full_org_id": "826049",
   "country": 826,
   "org_id": "049",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "British Harness Racing Club",
   "full_org_id": "826050",
   "country": 826,
   "org_id": "050",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "British Equestrian Federation",
   "full_org_id": "826051",
   "country": 826,
   "org_id": "051",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Hurlingham Polo Association",
   "full_org_id": "826052",
   "country": 826,
   "org_id": "052",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Caspian Breed Society (UK)",
   "full_org_id": "826053",
   "country": 826,
   "org_id": "053",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Coloured Horse and Pony Society UK",
   "full_org_id": "826054",
   "country": 826,
   "org_id": "054",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Scottish Icelandic Horse Association",
   "full_org_id": "826055",
   "country": 826,
   "org_id": "055",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Code for English Standard and Trotting Horses only",
   "full_org_id": "826056",
   "country": 826,
   "org_id": "056",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "British Bavarian Warmblood Association",
   "full_org_id": "826057",
   "country": 826,
   "org_id": "057",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Appaloosa Horse Club UK",
   "full_org_id": "826058",
   "country": 826,
   "org_id": "058",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Fjord Horse Registry of Scotland and Fjord Horse UK",
   "full_org_id": "826059",
   "country": 826,
   "org_id": "059",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Comann Each nan Eilean",
   "full_org_id": "826061",
   "country": 826,
   "org_id": "061",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "The American Saddlebred Association of Great Britain",
   "full_org_id": "826063",
   "country": 826,
   "org_id": "063",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "British Show Jumping Association",
   "full_org_id": "826064",
   "country": 826,
   "org_id": "064",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "The Haflinger Society of Great Britain",
   "full_org_id": "826065",
   "country": 826,
   "org_id": "065",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "The Miniature Mediterranean Donkey Association",
   "full_org_id": "826066",
   "country": 826,
   "org_id": "066",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "The Pleasure Horse Society",
   "full_org_id": "826067",
   "country": 826,
   "org_id": "067",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Horse Passport Agency Ltd",
   "full_org_id": "372069",
   "country": 372,
   "org_id": "069",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Horse Passport Agency Ltd",
   "full_org_id": "826069",
   "country": 826,
   "org_id": "069",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "The Lipizanner Society of GB",
   "full_org_id": "826070",
   "country": 826,
   "org_id": "070",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "The United Saddlebred Association UK",
   "full_org_id": "826071",
   "country": 826,
   "org_id": "071",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "The Clydesdale Horse Society",
   "full_org_id": "826072",
   "country": 826,
   "org_id": "072",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "The Pet-ID-JRC Horse Register",
   "full_org_id": "826073",
   "country": 826,
   "org_id": "073",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Veteran Horse Society",
   "full_org_id": "826075",
   "country": 826,
   "org_id": "075",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Selle Francais/EquiCours",
   "full_org_id": "826077",
   "country": 826,
   "org_id": "077",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "American Miniature Horse Club GB",
   "full_org_id": "826078",
   "country": 826,
   "org_id": "078",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "British Falabella Studbook",
   "full_org_id": "826079",
   "country": 826,
   "org_id": "079",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "British Camargue Horse Society",
   "full_org_id": "826080",
   "country": 826,
   "org_id": "080",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Lusitano Breed Society of Great Britain",
   "full_org_id": "826081",
   "country": 826,
   "org_id": "081",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "The Showjumping Association of Ireland - Ulster Region",
   "full_org_id": "826082",
   "country": 826,
   "org_id": "082",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "British Show Hack, Cob & Riding Horse Association",
   "full_org_id": "826084",
   "country": 826,
   "org_id": "084",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "The UK Knabstrupper Association",
   "full_org_id": "826087",
   "country": 826,
   "org_id": "087",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Weatherbys - Code for English TB and non TB horses only",
   "full_org_id": "8260GB",
   "country": 826,
   "org_id": "0GB",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Hauptverband für traberzucht und rennen eV",
   "full_org_id": "276307",
   "country": 276,
   "org_id": "307",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Verband der Zuchter des Arabischen Pferdes e.V.",
   "full_org_id": "276308",
   "country": 276,
   "org_id": "308",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Trakehner Verband e.V.",
   "full_org_id": "276309",
   "country": 276,
   "org_id": "309",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Zuchtverband fur deutsche Pferde e.V",
   "full_org_id": "276310",
   "country": 276,
   "org_id": "310",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Freisenpferde-Zuchtverband eV",
   "full_org_id": "276311",
   "country": 276,
   "org_id": "311",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Deutsche Quarter Horse Association",
   "full_org_id": "276312",
   "country": 276,
   "org_id": "312",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Zuchtverband für Shagya-Araber, Anglo-Araber und Araber e V",
   "full_org_id": "276313",
   "country": 276,
   "org_id": "313",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Paint Horse Club Germany e.V.",
   "full_org_id": "276314",
   "country": 276,
   "org_id": "314",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Lipizzaner Zuchtverband Deutschland e.V.",
   "full_org_id": "276316",
   "country": 276,
   "org_id": "316",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "European Colored Horses Association",
   "full_org_id": "276317",
   "country": 276,
   "org_id": "317",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Verband der Zuchter des Holsteiner Pferdes",
   "full_org_id": "276321",
   "country": 276,
   "org_id": "321",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Pferdestammbuch Schleswig-Holstein / Hamburg e V",
   "full_org_id": "276322",
   "country": 276,
   "org_id": "322",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Verband D Pferdezuchter Meckl-Vorpommern e.V",
   "full_org_id": "276327",
   "country": 276,
   "org_id": "327",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Verband D Pferdezuchter Meckl-Vorpommern e.V",
   "full_org_id": "276327",
   "country": 276,
   "org_id": "327",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Zuchtverband für das Ostfriesische u. Alt-Oldenburger Pferd e V",
   "full_org_id": "276330",
   "country": 276,
   "org_id": "330",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Verband hannoverscher Warmblutzüchter",
   "full_org_id": "276331",
   "country": 276,
   "org_id": "331",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Verband der Zuchter des Oldenburger Pferdes",
   "full_org_id": "276333",
   "country": 276,
   "org_id": "333",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Verband der Pony-und Kleinpferdezüchter Hannover e V",
   "full_org_id": "276334",
   "country": 276,
   "org_id": "334",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Pferdestammbuch Weser-Ems e V",
   "full_org_id": "276335",
   "country": 276,
   "org_id": "335",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Stammbuch für Kaltblutpferde Niedersachsens e V",
   "full_org_id": "276336",
   "country": 276,
   "org_id": "336",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Pferdezuchtverband Sachsen-Anhalt e.V",
   "full_org_id": "276337",
   "country": 276,
   "org_id": "337",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Westfälisches Pferdestammbuch e.V",
   "full_org_id": "276341",
   "country": 276,
   "org_id": "341",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Rheinisches Pferdestammbuch e.V",
   "full_org_id": "276343",
   "country": 276,
   "org_id": "343",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Pferdezuchtverband Rheinland-Pfalz-Saar",
   "full_org_id": "276351",
   "country": 276,
   "org_id": "351",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Pferdezuchtverband Berlin-Brandenburg",
   "full_org_id": "276357",
   "country": 276,
   "org_id": "357",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Verband Hessischer Pferdezüchter",
   "full_org_id": "276361",
   "country": 276,
   "org_id": "361",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Verband der Ponyzüchter Hessen e V",
   "full_org_id": "276363",
   "country": 276,
   "org_id": "363",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Deutscher Pinto Zuchtverband e.V.",
   "full_org_id": "276366",
   "country": 276,
   "org_id": "366",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Verband Thüringer Pferdezüchter e.V.",
   "full_org_id": "276367",
   "country": 276,
   "org_id": "367",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Pferdezuchtverband Baden-Württemberg",
   "full_org_id": "276373",
   "country": 276,
   "org_id": "373",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Pferdezuchtverband Baden-Württemberg",
   "full_org_id": "276373",
   "country": 276,
   "org_id": "373",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Landesverband Bayerischer Pferdezüchter",
   "full_org_id": "276381",
   "country": 276,
   "org_id": "381",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Bayerischer Zuchtverband für Kleinpferde und Specialpferderassen",
   "full_org_id": "276384",
   "country": 276,
   "org_id": "384",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Pferdezuchtverband Sachsen e.V",
   "full_org_id": "276387",
   "country": 276,
   "org_id": "387",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Hauptverband für traberzucht und rennen eV",
   "full_org_id": "276407",
   "country": 276,
   "org_id": "407",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Verband der Zuchter und Freunde des Arabischen Pferdes e.V.",
   "full_org_id": "276408",
   "country": 276,
   "org_id": "408",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Trakehner Verband e.V.",
   "full_org_id": "276409",
   "country": 276,
   "org_id": "409",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Zuchtverband fur deutsche Pferde e.V",
   "full_org_id": "276410",
   "country": 276,
   "org_id": "410",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Freisenpferde-Zuchtverband eV",
   "full_org_id": "276411",
   "country": 276,
   "org_id": "411",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Deutsche Quarter Horse Association",
   "full_org_id": "276412",
   "country": 276,
   "org_id": "412",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Zuchtverband für Shagya-Araber, Anglo-Araber und Araber e V",
   "full_org_id": "276413",
   "country": 276,
   "org_id": "413",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Paint Horse Club Germany e.V.",
   "full_org_id": "276414",
   "country": 276,
   "org_id": "414",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Horse Sport Ireland",
   "full_org_id": "372414",
   "country": 372,
   "org_id": "414",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Lipizzaner Zuchtverband Deutschland e.V.",
   "full_org_id": "276416",
   "country": 276,
   "org_id": "416",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "European Colored Horses Association",
   "full_org_id": "276417",
   "country": 276,
   "org_id": "417",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Verband der Zuchter des Holsteiner Pferdes",
   "full_org_id": "276421",
   "country": 276,
   "org_id": "421",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Pferdestammbuch Schleswig-Holstein / Hamburg e V",
   "full_org_id": "276422",
   "country": 276,
   "org_id": "422",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Verband D Pferdezuchter Meckl-Vorpommern e.V",
   "full_org_id": "276427",
   "country": 276,
   "org_id": "427",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Zuchtverband für das Ostfriesische u. Alt-Oldenburger Pferd e V",
   "full_org_id": "276430",
   "country": 276,
   "org_id": "430",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Verband hannoverscher Warmblutzüchter",
   "full_org_id": "276431",
   "country": 276,
   "org_id": "431",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Verband der Zuchter des Oldenburger Pferdes",
   "full_org_id": "276433",
   "country": 276,
   "org_id": "433",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Verband der Pony-und Kleinpferdezüchter Hannover e V",
   "full_org_id": "276434",
   "country": 276,
   "org_id": "434",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Pferdestammbuch Weser-Ems e V",
   "full_org_id": "276435",
   "country": 276,
   "org_id": "435",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Stammbuch für Kaltblutpferde Niedersachsens e V",
   "full_org_id": "276436",
   "country": 276,
   "org_id": "436",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Pferdezuchtverband Sachsen-Anhalt e.V",
   "full_org_id": "276437",
   "country": 276,
   "org_id": "437",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Westfälisches Pferdestammbuch e.V",
   "full_org_id": "276441",
   "country": 276,
   "org_id": "441",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Rheinisches Pferdestammbuch e.V",
   "full_org_id": "276443",
   "country": 276,
   "org_id": "443",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Pferdezuchtverband Rheinland-Pfalz-Saar",
   "full_org_id": "276451",
   "country": 276,
   "org_id": "451",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Pferdezuchtverband Sachsen-Thüringen",
   "full_org_id": "276455",
   "country": 276,
   "org_id": "455",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Pferdezuchtverband Berlin-Brandenburg",
   "full_org_id": "276457",
   "country": 276,
   "org_id": "457",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Verband Hessischer Pferdezüchter",
   "full_org_id": "276461",
   "country": 276,
   "org_id": "461",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Verband der Ponyzüchter Hessen e V",
   "full_org_id": "276463",
   "country": 276,
   "org_id": "463",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Deutscher Pinto Zuchtverband e.V.",
   "full_org_id": "276466",
   "country": 276,
   "org_id": "466",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Verband Thüringer Pferdezüchter e.V.",
   "full_org_id": "276467",
   "country": 276,
   "org_id": "467",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Pferdezuchtverband Baden-Württemberg",
   "full_org_id": "276473",
   "country": 276,
   "org_id": "473",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Verein der Freunde und Züchter des Berberpferdes e.V.",
   "full_org_id": "276478",
   "country": 276,
   "org_id": "478",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Appaloosa Horse Club Germany e.V. (ApHCG)",
   "full_org_id": "276479",
   "country": 276,
   "org_id": "479",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Landesverband Bayerischer Pferdezüchter",
   "full_org_id": "276481",
   "country": 276,
   "org_id": "481",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Bayerischer Zuchtverband für Kleinpferde und Specialpferderassen",
   "full_org_id": "276484",
   "country": 276,
   "org_id": "484",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Zuchtverband für Senner Pferde e.V.",
   "full_org_id": "276486",
   "country": 276,
   "org_id": "486",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Pferdezuchtverband Sachsen e.V",
   "full_org_id": "276487",
   "country": 276,
   "org_id": "487",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Landesverband Baden-Württemberg für Leistungsprüfungen in der Tierzucht e.V.",
   "full_org_id": "276501",
   "country": 276,
   "org_id": "501",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Beauftragte Stelle des Freistaats Bayern",
   "full_org_id": "276502",
   "country": 276,
   "org_id": "502",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "The Jockey Club of America (canadian TB only)",
   "full_org_id": "124CAN",
   "country": 124,
   "org_id": "CAN",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "French Horse - TB",
   "full_org_id": "2500FR",
   "country": 250,
   "org_id": "FR",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Direktorium für Vollblutzucht und Rennen",
   "full_org_id": "276GER",
   "country": 276,
   "org_id": "GER",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Weatherbys Ireland",
   "full_org_id": "372IRE",
   "country": 372,
   "org_id": "IRE",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "The Jockey Club of America",
   "full_org_id": "840USA",
   "country": 840,
   "org_id": "USA",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 },
 {
   "name": "Arab Horse Society of Zimbabwe",
   "full_org_id": "716001",
   "country": 716,
   "org_id": "001",
   "num_reg": 200,
   "source_of_num_reg": "Guess",
   "FIELD7": ""
 }
]